const entranceExams = [
    "JEE Main",
    "Jee",
    "CAT",
    "MAT",
    "NEET",
    "CMAT",
    "XAT",
    "AP ECET",
    "MHT CET",
    "CUET PG",
    "UPTAC",
    "TNEA",
    "ATMA",
    "NEET PG",
    "CUET",
    "TANCET",
    "NATA",
    "AYUSH NEET Counselling",
    "MAHCET",
    "GATE",
    "Karnataka PGCET",
    "KCET",
    "Maharashtra JEE Main",
    "AP EAPCET",
    "TS EAMCET",
    "WB CAP",
    "GPAT",
    "GMAT",
    "APICET",
    "NEET MDS",
    "MP Counselling",
    "KEAM",
    "NEET SS",
    "AP PGECET",
    "Gujarat ACPC",
    "TSICET",
    "TS PGECET",
    "KMAT",
    "GUJCET",
    "UP BEd JEE",
    "COMEDK UGET",
    "CLAT",
    "OJEE",
    "AP OAMDC",
    "NMAT",
    "MAH MCA CET",
    "AP POLYCET",
    "WBJEE",
    "HSTES",
    "JELET",
    "IPU CET",
    "TS DOST",
    "Karnataka NEET Counselling",
    "MH CET LAW",
    "NCHMCT JEE",
    "REAP",
    "AIAPGET",
    "JEE Advanced",
    "UCEED",
    "CLAT PG",
    "AIDAT",
    "CEETA PG",
    "Uttar Pradesh NEET Counselling",
    "AILET",
    "Tamil Nadu NEET Counselling",
    "KMAT KERALA",
    "Maharashtra NEET Counselling",
    "IIT JAM",
    "Chattisgarh Pre Engineering Test",
    "Bihar BEd CET",
    "Kerala NEET Counselling",
    "WBJEE ANM GNM",
    "Rajasthan NEET Counselling",
    "LSAT",
    "TS POLYCET",
    "AIMA UGAT",
    "DASA",
    "GAHET",
    "LEET",
    "WBJEE JENPAS UG",
    "Bihar UGEAC",
    "JEMAT",
    "NTA PhD Entrance Exam",
    "Gujarat NEET Counselling",
    "UP NEET PG Counselling",
    "DUET",
    "West Bengal NEET Counselling",
    "Tamil Nadu NEET PG Counselling",
    "MAH BEd CET",
    "PPMET",
    "JNU CEEB",
    "NIFT",
    "CEED",
    "JEECUP",
    "Andhra Pradesh NEET Counselling",
    "SNAP",
    "ILICAT",
    "CCMN",
    "Madhya Pradesh NEET Counselling",
    "AP EDCET",
    "INI CET",
    "Odisha CPET",
    "NID",
    "MAH M Arch CET",
    "Kerala NEET PG Counselling",
    "GRE",
    "NIMCET",
    "WB JECA",
    "UGMAC",
    "CENTAC",
    "MP Pre BEd",
    "Rajasthan JET",
    "WB NEET PG Counselling",
    "AP LAWCET",
    "COAP",
    "Punjab NEET Counselling",
    "RMCAAT",
    "KLEE",
    "Andhra Pradesh NEET PG Counselling",
    "IMU CET",
    "Haryana NEET Counselling",
    "INI SS",
    "TS EDCET",
    "NPAT",
    "MP NEET PG Counselling",
    "HPU BEd",
    "AIMA RMAT",
    "Gujarat NEET PG Counselling",
    "UKSEE",
    "CG Pre BEd",
    "AIEED",
    "Odisha NEET Counselling",
    "JCECE",
    "IBSAT",
    "SET",
    "CG PRE MCA",
    "WBUT PGET",
    "Amity JEE",
    "TANATA",
    "Himachal Pradesh NEET Counselling",
    "AIIMS BSc Nursing",
    "Assam CEE",
    "HPCET",
    "Kerala MCA",
    "MAH BHMCT CET",
    "TS PGLCET",
    "FDDI AIST",
    "MET",
    "AIIMS PG",
    "KIITEE",
    "MCAER PG CET",
    "AP PGLCET",
    "TS LAWCET",
    "SUAT",
    "BPTPIA CET",
    "GAT B",
    "ISI Admission Test",
    "JEECE",
    "AIIMS MSc",
    "NIPER JEE",
    "RTU CAM",
    "SOFT CET",
    "JSAT",
    "SRMJEEE",
    "IISER",
    "BCECE",
    "HPU MAT",
    "AEEE",
    "CG PPHT",
    "IIHM ECHAT",
    "OUCET",
    "UBTER JEEP",
    "JAC Delhi",
    "AIIMS Paramedical",
    "UPCATET",
    "MDUCEE",
    "ABVMU CNET",
    "Haryana NEET PG Counselling",
    "IIMC",
    "CUSAT CAT",
    "GLAET",
    "HCEE",
    "ITM NEST",
    "AUCET",
    "AMIETE",
    "IPMAT",
    "Tripura NEET Counselling",
    "Chhattisgarh NEET PG Counselling",
    "VITEEE",
    "IIFT",
    "BIT MCA",
    "RPVT",
    "Gujarat PGECET",
    "JAC Chandigarh",
    "Jharkhand NEET Counselling",
    "BVP CET",
    "DU JAT",
    "BUMAT",
    "KU CAT",
    "MGU CAT",
    "VITMEE",
    "RUET",
    "JUET",
    "BHU PET",
    "ULSAT",
    "CG PAT",
    "AIBE",
    "UPESMET",
    "BMAT",
    "NMIMS Entrance Test",
    "SLAT",
    "Himachal Pradesh NEET PG Counselling",
    "TISSNET",
    "BITSAT",
    "JKCET",
    "DU LLB",
    "RPET Pharmacy",
    "DPU AIBTCET",
    "IGNOU BEd Entrance Test",
    "HORTICET",
    "Rajasthan LEEP",
    "DSAT",
    "CUEE",
    "IEMJEE",
    "AUAT",
    "CEE AMPAI",
    "PU LLB",
    "BITS HD",
    "KRLMPCA CET",
    "MAH AAC CET",
    "Rajasthan PTET",
    "APJEE",
    "UPES DAT",
    "PU CET",
    "AU AIMEE Pharmacy",
    "AAEEE",
    "BHU UET",
    "SLIET SET",
    "ITSAT",
    "PESSAT",
    "GVSAT",
    "UPESEAT",
    "BEEE",
    "JUEE",
    "Andhra University Engineering Entrance Test",
    "REVA EET",
    "IUET",
    "SAAT",
    "UP Veterinary Entrance Exam",
    "OUAT",
    "Allahabad University PGAT",
    "TUEE",
    "PGIMER",
    "RULET",
    "TISS BAT",
    "FTII Entrance Exam",
    "BEET",
    "MZUEEE",
    "LFAT",
    "Allahabad University LAT",
    "Jain Entrance Test",
    "JIPMAT",
    "TS ECET",
    "UPCET",
    "NERIST Entrance Exam",
    "IIITH PGEE",
    "GCET",
    "MICAT",
    "AMUEEE",
    "DNB CET",
    "NEST",
    "BLAT",
    "Tripura JEE",
    "SRMCAT",
    "LPUNEST",
    "JIPMER",
    "KLUEEE",
    "ANUPGCET",
    "HITSEEE",
    "AISEEE",
    "VTUEEE",
    "CIEAT",
    "VSAT",
    "CMRUAT",
    "DAVUET",
    "SPSAT",
    "SRMS EET",
    "VEE",
    "PUCAT",
    "AAU VET",
    "YVUCET",
    "FRI MSc",
    "DUCET",
    "PULEET",
    "AIHMCT WAT",
    "MUCMET",
    "IIAD Entrance Exam",
    "XIC OET",
    "IICD",
    "VMOU BEd Entrance Exam",
    "GLS Institute of Design DAT",
    "APIIT NAT",
    "KLEU AIET",
    "EMAT",
    "GNIHM JET",
    "MUJEE",
    "Q Care",
    "SAEEE",
    "SMAT",
    "SRMHCAT",
    "DNB PDCET",
    "DAVV CET",
    "IIITH UGEE",
    "GMCET",
    "AME CEE",
    "JKLU DET",
    "CSAB Counselling",
    "Karnataka DCET",
    "PUBDET",
    "SMIT",
    "KIITEE Management"
]

export default entranceExams;
